name: CI & Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-tests:
    name: Run PHP Tests
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP & Composer via Homebrew
        run: |
          brew install php@8.2
          brew install composer
          echo "/opt/homebrew/opt/php@8.2/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: |
          echo "APP_KEY=$(php artisan key:generate --show --no-interaction)" >> .env

      - name: Run Feature Tests
        run: php artisan test --testsuite=Feature -v

  build:
    name: Build TypeScript
    needs: php-tests
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache JS dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: js-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: js-${{ runner.os }}-

      - name: Install dependencies (Bun)
        run: bun install --frozen-lockfile

      - name: Compile TypeScript
        run: bun run tsc

  publish:
    name: Publish to npm
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish to npm (Bun)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun publish --access public
