name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-tests:
    name: Run PHP Tests
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PHP & Composer via Homebrew
        run: |
          brew install php@8.2
          brew install composer
          echo "/opt/homebrew/opt/php@8.2/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: |
          echo "APP_KEY=$(php artisan key:generate --show --no-interaction)" >> .env

      - name: Run Pest Tests
        run: vendor/bin/pest --verbose
