name: CI & Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-tests:
    name: Run PHP Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, sqlite, xml, ctype, json

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Pest Tests
        run: vendor/bin/pest --stop-on-failure

  build:
    name: Build TypeScript
    needs: php-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (Bun)
        run: bun install --frozen-lockfile

      - name: Compile TypeScript
        run: bun run tsc

  publish:
    name: Publish to npm
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun (latest)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Publish to npm (Bun)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun publish --access public
