name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-tests:
    name: Run PHP Tests
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:2

      - name: Cache vendor directory
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: |
          echo "APP_KEY=$(php artisan key:generate --show --no-interaction)" >> .env

      - name: Run Pest Tests
        run: php artisan test --parallel
